<nav>
    <a href="./index.php">Home</a>
    <a href="./jobs.php">Position Descriptions</a>
    <a href="./apply.php">Apply</a>
    <a href="./about.php">Group Details</a>
    <a href="./enhancements.php">Enhancements</a>
    <a href="./enhancements2.php">PHP Enhancements</a>
    <a href="mailto:lukewarmassociates@gmail.com?subject=Re. Lukewarm Associates">Contact Us</a>
    <a href="./login.php">Login</a>
</nav>